kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: shoeb-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-shoeb
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
