apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: shoeb-namespace
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
