kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  namespace: shoeb-namespace

spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
