kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: shoeb-namespace
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  