apiVersion: v1
kind: Pod
metadata:
  name: init-test

spec:
  initContainers:
    - name: init-container
      image: busybox:latest
      command: [
          "sh",
          "-c",
          "echo 'Initialization started ....'; sleep 10;
          echo 'Initialization complete'",
        ]
  containers:
    - name: main-container
      image: busybox:latest
      command: ["sh", "-c", "echo 'Main container started' "]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
